server {

	server_name soulogic.com;

	listen [::]:443 ssl;

	ssl_certificate	    ssl.d/soulogic.com.crt;
	ssl_certificate_key ssl.d/soulogic.com.key;

	access_log /log/soulogic/access.log;
	error_log  /log/soulogic/error.log;

	root /www/memoria/public;

	location /font {
		add_header Cache-Control "public, max-age=31536000, immutable";
		add_header Last-Modified "";
	}

	location /ip {
		default_type text/plain;
		return 200 "$remote_addr";
	}

	location /metrics/ {
		gzip_proxied off;
		proxy_hide_header Accept-Ranges;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Proto https;
		proxy_pass_header Server;
		proxy_pass_header ETag;
		proxy_pass http://127.0.0.1:21005;
		access_log off;
		log_not_found off;
	}

	location / {
		proxy_pass_request_headers on;
        proxy_http_version 1.1;
        gzip off;
        proxy_cache off;
        proxy_buffering off;
        gzip_proxied off;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
        proxy_connect_timeout 75s;
        proxy_buffer_size 4096;
        proxy_request_buffering off;
        keepalive_timeout 86400s;
        send_timeout 86400s;

		proxy_hide_header Accept-Ranges;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Proto https;
		proxy_pass_header Server;
		proxy_pass_header ETag;
		proxy_pass http://127.0.0.1:21005;
	}

	location = /robots.txt  {
		access_log off; 
		log_not_found off;
	}

	location = /favicon.ico {
		expires max;
		access_log off;
		log_not_found off;
	}

	location = /favicon.webp {
		expires max;
		access_log off;
		log_not_found off;
	}
}

server {

	server_name soulogic.com;

	listen [::]:80;

	access_log /log/soulogic/access.log;
	error_log  /log/soulogic/error.log;

	root /www/memoria/public;

	location /ip {
		default_type text/plain;
		return 200 "$remote_addr";
	}

	location / {
		gzip_proxied off;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-Proto http;
		proxy_pass http://127.0.0.1:21005;
		proxy_pass_header Server;
	}

	location = /robots.txt  {
		access_log off; 
		log_not_found off;
	}

	location = /favicon.ico {
		expires max;
		access_log off;
		log_not_found off;
	}

	location = /favicon.webp {
		expires max;
		access_log off;
		log_not_found off;
	}
}
