server {

	server_name memoria.tanya.9farm.com;

	listen [::]:443 ssl;

	ssl_certificate	    ssl.d/tanya.9farm.com.crt;
	ssl_certificate_key ssl.d/tanya.9farm.com.key;

	access_log /log/memoria/access.log;
	error_log  /log/memoria/error.log;

	root /www/memoria/client/dist-git;

	location /public/ {
		rewrite ^/public/(.*)$ https://soulogic.tanya.9farm.com/$1 redirect;
	}

    location /file {
        proxy_pass http://127.0.0.1:21005;
	}

    location /api/upload {
		client_max_body_size 100M;
        proxy_pass http://127.0.0.1:21006;
	}

    location / {
        proxy_pass http://127.0.0.1:21006;
	}

	location = /robots.txt  {
		access_log off; log_not_found off;
	}

	location = /favicon.ico {
		expires max;
		access_log off;
		log_not_found off;
	}
}

server {

	server_name memoria.tanya.9farm.com;

	listen [::]:80;

	location / {
		return 301 https://$host$request_uri;
	}
}
